### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [jguzmanjr1/prj-rev-bwfs-dasmoto#6]
https://github.com/jguzmanjr1/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20Arts/Resources/style.css#L20-L22

You're repeating this style a lot throughout your CSS, and you missed applying it to the `h3` elements.

When a style should be applied by default, it's best to create a rule with a universal selector for it so it's applied everywhere right away.

```css
* {
  font-family: Helvetica;
}
```

Alternatively, if you've got a style that should be applied to multiple elements but not all of them, you could list them out in the selector.

```css
h1, h2, span {
  font-weight: bold;
}
```
